name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Run Tests
      run: go test -v ./test

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v4
    #   with:
    #     fetch-depth: 0

    # - name: Setup Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.25'

    # - name: Run Tests
    #   run: go test -v ./test

    - name: Generate Semantic Version
      id: semver
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        major_pattern: "^(.*)(!|BREAKING CHANGE)(.*)$"
        minor_pattern: "^feat(\\(.+\\))?:"
        patch_pattern: "^fix(\\(.+\\))?:"
        version_format: "${major}.${minor}.${patch}"
        bump_each_commit: false

    - name: Create and Push Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.semver.outputs.version_tag }}
        git push origin ${{ steps.semver.outputs.version_tag }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ steps.semver.outputs.version }}
        sbom: true